import type { Metadata } from 'next'
import { Libre_Baskerville } from 'next/font/google'

import './globals.css'

const liberSans = Libre_Baskerville({ variable: '--font-libre-sans', subsets: ['latin'] })

// TODO: Update metadata
export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' }

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`${liberSans.variable} font-sans antialiased`}>{children}</body>
    </html>
  )
}
